//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.Buy = new HashSet<Buy>();
        }
    
        public int ID_tovar { get; set; }
        public string Name { get; set; }
        public int Category { get; set; }
        public string Provider { get; set; }
        public string Price { get; set; }
        public string Amount { get; set; }
        public System.DateTime DateDelivery { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string info { get { return ID_tovar + " - " + Name; } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buy> Buy { get; set; }
        public virtual Category Category1 { get; set; }
    }
}
